platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'BFRImageViewer' do

pod 'DACircularProgress'
pod 'SDWebImage', '~> 3.7'

end

target 'BFRImageViewerTests' do

end

target 'BFRImageViewerUITests' do

end
