# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BFRImageViewer' do

pod 'DACircularProgress'
pod 'SDWebImage', '~> 3.7'

end

target 'BFRImageViewerTests' do

end

target 'BFRImageViewerUITests' do

end
